# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af5628258431874426d13514e39fde62aae95ec0a65da7bae718a1e955baa068361d340d991c7b59a88f446af7cff7de98debdc5df7f8c2b548be938534763c0

test:
  secret_key_base: 71b50b8cb7f8c7e9855eb7525586de6d7185dae5bba4c3c7fb384e8a9cd06a8194b4626bf2c60641c954614c1b82038bdbb53fee14b22925ecfc99e47dc348fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
